#!/usr/bin/python
#coding=utf-8
#Filename:definedtypes.py

class IfcDoorStyleOperationEnum():
    """"""
    SINGLE_SWING_LEFT=0
    SINGLE_SWING_RIGHT=1
    DOUBLE_DOOR_SINGLE_SWING=2
    DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_LEFT=3
    DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_RIGHT=4
    DOUBLE_SWING_LEFT=5
    DOUBLE_SWING_RIGHT=6
    DOUBLE_DOOR_DOUBLE_SWING=7
    SLIDING_TO_LEFT=8
    SLIDING_TO_RIGHT=9
    DOUBLE_DOOR_SLIDING=10
    FOLDING_TO_LEFT=11
    FOLDING_TO_RIGHT=12
    DOUBLE_DOOR_FOLDING=13
    REVOLVING=14
    ROLLINGUP=15
    USERDEFINED=16
    NOTDEFINED=17
 
class IfcElectricTimeControlTypeEnum():
    """"""
    TIMECLOCK=0
    TIMEDELAY=1
    RELAY=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcAirTerminalTypeEnum():
    """"""
    GRILLE=0
    REGISTER=1
    DIFFUSER=2
    EYEBALL=3
    IRIS=4
    LINEARGRILLE=5
    LINEARDIFFUSER=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcProjectOrderTypeEnum():
    """"""
    CHANGEORDER=0
    MAINTENANCEWORKORDER=1
    MOVEORDER=2
    PURCHASEORDER=3
    WORKORDER=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcSequenceEnum():
    """"""
    START_START=0
    START_FINISH=1
    FINISH_START=2
    FINISH_FINISH=3
    NOTDEFINED=4
 
class IfcRibPlateDirectionEnum():
    """"""
    DIRECTION_X=0
    DIRECTION_Y=1
 
class IfcSensorTypeEnum():
    """"""
    CO2SENSOR=0
    FIRESENSOR=1
    FLOWSENSOR=2
    GASSENSOR=3
    HEATSENSOR=4
    HUMIDITYSENSOR=5
    LIGHTSENSOR=6
    MOISTURESENSOR=7
    MOVEMENTSENSOR=8
    PRESSURESENSOR=9
    SMOKESENSOR=10
    SOUNDSENSOR=11
    TEMPERATURESENSOR=12
    USERDEFINED=13
    NOTDEFINED=14
 
class IfcElectricHeaterTypeEnum():
    """"""
    ELECTRICPOINTHEATER=0
    ELECTRICCABLEHEATER=1
    ELECTRICMATHEATER=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcObjectiveEnum():
    """"""
    CODECOMPLIANCE=0
    DESIGNINTENT=1
    HEALTHANDSAFETY=2
    REQUIREMENT=3
    SPECIFICATION=4
    TRIGGERCONDITION=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcColumnTypeEnum():
    """"""
    COLUMN=0
    USERDEFINED=1
    NOTDEFINED=2
 
class IfcGasTerminalTypeEnum():
    """"""
    GASAPPLIANCE=0
    GASBOOSTER=1
    GASBURNER=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcBuildingElementProxyTypeEnum():
    """"""
    USERDEFINED=0
    NOTDEFINED=1
 
class IfcJunctionBoxTypeEnum():
    """"""
    USERDEFINED=0
    NOTDEFINED=1
 
class IfcActionSourceTypeEnum():
    """"""
    DEAD_LOAD_G=0
    COMPLETION_G1=1
    LIVE_LOAD_Q=2
    SNOW_S=3
    WIND_W=4
    PRESTRESSING_P=5
    SETTLEMENT_U=6
    TEMPERATURE_T=7
    EARTHQUAKE_E=8
    FIRE=9
    IMPULSE=10
    IMPACT=11
    TRANSPORT=12
    ERECTION=13
    PROPPING=14
    SYSTEM_IMPERFECTION=15
    SHRINKAGE=16
    CREEP=17
    LACK_OF_FIT=18
    BUOYANCY=19
    ICE=20
    CURRENT=21
    WAVE=22
    RAIN=23
    BRAKES=24
    USERDEFINED=25
    NOTDEFINED=26
 
class IfcSIUnitName():
    """"""
    AMPERE=0
    BECQUEREL=1
    CANDELA=2
    COULOMB=3
    CUBIC_METRE=4
    DEGREE_CELSIUS=5
    FARAD=6
    GRAM=7
    GRAY=8
    HENRY=9
    HERTZ=10
    JOULE=11
    KELVIN=12
    LUMEN=13
    LUX=14
    METRE=15
    MOLE=16
    NEWTON=17
    OHM=18
    PASCAL=19
    RADIAN=20
    SECOND=21
    SIEMENS=22
    SIEVERT=23
    SQUARE_METRE=24
    STERADIAN=25
    TESLA=26
    VOLT=27
    WATT=28
    WEBER=29
 
class IfcMemberTypeEnum():
    """"""
    BRACE=0
    CHORD=1
    COLLAR=2
    MEMBER=3
    MULLION=4
    PLATE=5
    POST=6
    PURLIN=7
    RAFTER=8
    STRINGER=9
    STRUT=10
    STUD=11
    USERDEFINED=12
    NOTDEFINED=13
 
class IfcDoorStyleConstructionEnum():
    """"""
    ALUMINIUM=0
    HIGH_GRADE_STEEL=1
    STEEL=2
    WOOD=3
    ALUMINIUM_WOOD=4
    ALUMINIUM_PLASTIC=5
    PLASTIC=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcDirectionSenseEnum():
    """"""
    POSITIVE=0
    NEGATIVE=1
 
class IfcNullStyle():
    """"""
    NULL=0
 
class IfcRampFlightTypeEnum():
    """"""
    STRAIGHT=0
    SPIRAL=1
    USERDEFINED=2
    NOTDEFINED=3
 
class IfcWindowStyleOperationEnum():
    """"""
    SINGLE_PANEL=0
    DOUBLE_PANEL_VERTICAL=1
    DOUBLE_PANEL_HORIZONTAL=2
    TRIPLE_PANEL_VERTICAL=3
    TRIPLE_PANEL_BOTTOM=4
    TRIPLE_PANEL_TOP=5
    TRIPLE_PANEL_LEFT=6
    TRIPLE_PANEL_RIGHT=7
    TRIPLE_PANEL_HORIZONTAL=8
    USERDEFINED=9
    NOTDEFINED=10
 
class IfcBooleanOperator():
    """"""
    UNION=0
    INTERSECTION=1
    DIFFERENCE=2
 
class IfcDuctFittingTypeEnum():
    """"""
    BEND=0
    CONNECTOR=1
    ENTRY=2
    EXIT=3
    JUNCTION=4
    OBSTRUCTION=5
    TRANSITION=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcCurrencyEnum():
    """"""
    AED=0
    AES=1
    ATS=2
    AUD=3
    BBD=4
    BEG=5
    BGL=6
    BHD=7
    BMD=8
    BND=9
    BRL=10
    BSD=11
    BWP=12
    BZD=13
    CAD=14
    CBD=15
    CHF=16
    CLP=17
    CNY=18
    CYS=19
    CZK=20
    DDP=21
    DEM=22
    DKK=23
    EGL=24
    EST=25
    EUR=26
    FAK=27
    FIM=28
    FJD=29
    FKP=30
    FRF=31
    GBP=32
    GIP=33
    GMD=34
    GRX=35
    HKD=36
    HUF=37
    ICK=38
    IDR=39
    ILS=40
    INR=41
    IRP=42
    ITL=43
    JMD=44
    JOD=45
    JPY=46
    KES=47
    KRW=48
    KWD=49
    KYD=50
    LKR=51
    LUF=52
    MTL=53
    MUR=54
    MXN=55
    MYR=56
    NLG=57
    NZD=58
    OMR=59
    PGK=60
    PHP=61
    PKR=62
    PLN=63
    PTN=64
    QAR=65
    RUR=66
    SAR=67
    SCR=68
    SEK=69
    SGD=70
    SKP=71
    THB=72
    TRL=73
    TTD=74
    TWD=75
    USD=76
    VEB=77
    VND=78
    XEU=79
    ZAR=80
    ZWD=81
    NOK=82
 
class IfcObjectTypeEnum():
    """"""
    PRODUCT=0
    PROCESS=1
    CONTROL=2
    RESOURCE=3
    ACTOR=4
    GROUP=5
    PROJECT=6
    NOTDEFINED=7
 
class IfcThermalLoadTypeEnum():
    """"""
    SENSIBLE=0
    LATENT=1
    RADIANT=2
    NOTDEFINED=3
 
class IfcBSplineCurveForm():
    """"""
    POLYLINE_FORM=0
    CIRCULAR_ARC=1
    ELLIPTIC_ARC=2
    PARABOLIC_ARC=3
    HYPERBOLIC_ARC=4
    UNSPECIFIED=5
 
class IfcElementCompositionEnum():
    """"""
    COMPLEX=0
    ELEMENT=1
    PARTIAL=2
 
class IfcGeometricProjectionEnum():
    """"""
    GRAPH_VIEW=0
    SKETCH_VIEW=1
    MODEL_VIEW=2
    PLAN_VIEW=3
    REFLECTED_PLAN_VIEW=4
    SECTION_VIEW=5
    ELEVATION_VIEW=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcReflectanceMethodEnum():
    """"""
    BLINN=0
    FLAT=1
    GLASS=2
    MATT=3
    METAL=4
    MIRROR=5
    PHONG=6
    PLASTIC=7
    STRAUSS=8
    NOTDEFINED=9
 
class IfcSlabTypeEnum():
    """"""
    FLOOR=0
    ROOF=1
    LANDING=2
    BASESLAB=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcInternalOrExternalEnum():
    """"""
    INTERNAL=0
    EXTERNAL=1
    NOTDEFINED=2
 
class IfcDimensionExtentUsage():
    """"""
    ORIGIN=0
    TARGET=1
 
class IfcPipeFittingTypeEnum():
    """"""
    BEND=0
    CONNECTOR=1
    ENTRY=2
    EXIT=3
    JUNCTION=4
    OBSTRUCTION=5
    TRANSITION=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcSanitaryTerminalTypeEnum():
    """"""
    BATH=0
    BIDET=1
    CISTERN=2
    SHOWER=3
    SINK=4
    SANITARYFOUNTAIN=5
    TOILETPAN=6
    URINAL=7
    WASHHANDBASIN=8
    WCSEAT=9
    USERDEFINED=10
    NOTDEFINED=11
 
class IfcWallTypeEnum():
    """"""
    STANDARD=0
    POLYGONAL=1
    SHEAR=2
    ELEMENTEDWALL=3
    PLUMBINGWALL=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcUnitaryEquipmentTypeEnum():
    """"""
    AIRHANDLER=0
    AIRCONDITIONINGUNIT=1
    SPLITSYSTEM=2
    ROOFTOPUNIT=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcProcedureTypeEnum():
    """"""
    ADVICE_CAUTION=0
    ADVICE_NOTE=1
    ADVICE_WARNING=2
    CALIBRATION=3
    DIAGNOSTIC=4
    SHUTDOWN=5
    STARTUP=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcDistributionChamberElementTypeEnum():
    """"""
    FORMEDDUCT=0
    INSPECTIONCHAMBER=1
    INSPECTIONPIT=2
    MANHOLE=3
    METERCHAMBER=4
    SUMP=5
    TRENCH=6
    VALVECHAMBER=7
    USERDEFINED=8
    NOTDEFINED=9
 
class IfcTextPath():
    """"""
    LEFT=0
    RIGHT=1
    UP=2
    DOWN=3
 
class IfcCostScheduleTypeEnum():
    """"""
    BUDGET=0
    COSTPLAN=1
    ESTIMATE=2
    TENDER=3
    PRICEDBILLOFQUANTITIES=4
    UNPRICEDBILLOFQUANTITIES=5
    SCHEDULEOFRATES=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcFanTypeEnum():
    """"""
    CENTRIFUGALFORWARDCURVED=0
    CENTRIFUGALRADIAL=1
    CENTRIFUGALBACKWARDINCLINEDCURVED=2
    CENTRIFUGALAIRFOIL=3
    TUBEAXIAL=4
    VANEAXIAL=5
    PROPELLORAXIAL=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcAheadOrBehind():
    """"""
    AHEAD=0
    BEHIND=1
 
class IfcCooledBeamTypeEnum():
    """"""
    ACTIVE=0
    PASSIVE=1
    USERDEFINED=2
    NOTDEFINED=3
 
class IfcFireSuppressionTerminalTypeEnum():
    """"""
    BREECHINGINLET=0
    FIREHYDRANT=1
    HOSEREEL=2
    SPRINKLER=3
    SPRINKLERDEFLECTOR=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcDocumentConfidentialityEnum():
    """"""
    PUBLIC=0
    RESTRICTED=1
    CONFIDENTIAL=2
    PERSONAL=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcAirTerminalBoxTypeEnum():
    """"""
    CONSTANTFLOW=0
    VARIABLEFLOWPRESSUREDEPENDANT=1
    VARIABLEFLOWPRESSUREINDEPENDANT=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcDerivedUnitEnum():
    """"""
    ANGULARVELOCITYUNIT=0
    COMPOUNDPLANEANGLEUNIT=1
    DYNAMICVISCOSITYUNIT=2
    HEATFLUXDENSITYUNIT=3
    INTEGERCOUNTRATEUNIT=4
    ISOTHERMALMOISTURECAPACITYUNIT=5
    KINEMATICVISCOSITYUNIT=6
    LINEARVELOCITYUNIT=7
    MASSDENSITYUNIT=8
    MASSFLOWRATEUNIT=9
    MOISTUREDIFFUSIVITYUNIT=10
    MOLECULARWEIGHTUNIT=11
    SPECIFICHEATCAPACITYUNIT=12
    THERMALADMITTANCEUNIT=13
    THERMALCONDUCTANCEUNIT=14
    THERMALRESISTANCEUNIT=15
    THERMALTRANSMITTANCEUNIT=16
    VAPORPERMEABILITYUNIT=17
    VOLUMETRICFLOWRATEUNIT=18
    ROTATIONALFREQUENCYUNIT=19
    TORQUEUNIT=20
    MOMENTOFINERTIAUNIT=21
    LINEARMOMENTUNIT=22
    LINEARFORCEUNIT=23
    PLANARFORCEUNIT=24
    MODULUSOFELASTICITYUNIT=25
    SHEARMODULUSUNIT=26
    LINEARSTIFFNESSUNIT=27
    ROTATIONALSTIFFNESSUNIT=28
    MODULUSOFSUBGRADEREACTIONUNIT=29
    ACCELERATIONUNIT=30
    CURVATUREUNIT=31
    HEATINGVALUEUNIT=32
    IONCONCENTRATIONUNIT=33
    LUMINOUSINTENSITYDISTRIBUTIONUNIT=34
    MASSPERLENGTHUNIT=35
    MODULUSOFLINEARSUBGRADEREACTIONUNIT=36
    MODULUSOFROTATIONALSUBGRADEREACTIONUNIT=37
    PHUNIT=38
    ROTATIONALMASSUNIT=39
    SECTIONAREAINTEGRALUNIT=40
    SECTIONMODULUSUNIT=41
    SOUNDPOWERUNIT=42
    SOUNDPRESSUREUNIT=43
    TEMPERATUREGRADIENTUNIT=44
    THERMALEXPANSIONCOEFFICIENTUNIT=45
    WARPINGCONSTANTUNIT=46
    WARPINGMOMENTUNIT=47
    USERDEFINED=48
 
class IfcLightEmissionSourceEnum():
    """"""
    COMPACTFLUORESCENT=0
    FLUORESCENT=1
    HIGHPRESSUREMERCURY=2
    HIGHPRESSURESODIUM=3
    LIGHTEMITTINGDIODE=4
    LOWPRESSURESODIUM=5
    LOWVOLTAGEHALOGEN=6
    MAINVOLTAGEHALOGEN=7
    METALHALIDE=8
    TUNGSTENFILAMENT=9
    NOTDEFINED=10
 
class IfcCableCarrierFittingTypeEnum():
    """"""
    BEND=0
    CROSS=1
    REDUCER=2
    TEE=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcPumpTypeEnum():
    """"""
    CIRCULATOR=0
    ENDSUCTION=1
    SPLITCASE=2
    VERTICALINLINE=3
    VERTICALTURBINE=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcProjectOrderRecordTypeEnum():
    """"""
    CHANGE=0
    MAINTENANCE=1
    MOVE=2
    PURCHASE=3
    WORK=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcWindowStyleConstructionEnum():
    """"""
    ALUMINIUM=0
    HIGH_GRADE_STEEL=1
    STEEL=2
    WOOD=3
    ALUMINIUM_WOOD=4
    PLASTIC=5
    OTHER_CONSTRUCTION=6
    NOTDEFINED=7
 
class IfcCableSegmentTypeEnum():
    """"""
    CABLESEGMENT=0
    CONDUCTORSEGMENT=1
    USERDEFINED=2
    NOTDEFINED=3
 
class IfcWasteTerminalTypeEnum():
    """"""
    FLOORTRAP=0
    FLOORWASTE=1
    GULLYSUMP=2
    GULLYTRAP=3
    GREASEINTERCEPTOR=4
    OILINTERCEPTOR=5
    PETROLINTERCEPTOR=6
    ROOFDRAIN=7
    WASTEDISPOSALUNIT=8
    WASTETRAP=9
    USERDEFINED=10
    NOTDEFINED=11
 
class IfcRoofTypeEnum():
    """"""
    FLAT_ROOF=0
    SHED_ROOF=1
    GABLE_ROOF=2
    HIP_ROOF=3
    HIPPED_GABLE_ROOF=4
    GAMBREL_ROOF=5
    MANSARD_ROOF=6
    BARREL_ROOF=7
    RAINBOW_ROOF=8
    BUTTERFLY_ROOF=9
    PAVILION_ROOF=10
    DOME_ROOF=11
    FREEFORM=12
    NOTDEFINED=13
 
class IfcRoleEnum():
    """"""
    SUPPLIER=0
    MANUFACTURER=1
    CONTRACTOR=2
    SUBCONTRACTOR=3
    ARCHITECT=4
    STRUCTURALENGINEER=5
    COSTENGINEER=6
    CLIENT=7
    BUILDINGOWNER=8
    BUILDINGOPERATOR=9
    MECHANICALENGINEER=10
    ELECTRICALENGINEER=11
    PROJECTMANAGER=12
    FACILITIESMANAGER=13
    CIVILENGINEER=14
    COMISSIONINGENGINEER=15
    ENGINEER=16
    OWNER=17
    CONSULTANT=18
    CONSTRUCTIONMANAGER=19
    FIELDCONSTRUCTIONMANAGER=20
    RESELLER=21
    USERDEFINED=22
 
class IfcPileTypeEnum():
    """"""
    COHESION=0
    FRICTION=1
    SUPPORT=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcElectricCurrentEnum():
    """"""
    ALTERNATING=0
    DIRECT=1
    NOTDEFINED=2
 
class IfcFilterTypeEnum():
    """"""
    AIRPARTICLEFILTER=0
    ODORFILTER=1
    OILFILTER=2
    STRAINER=3
    WATERFILTER=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcTransformerTypeEnum():
    """"""
    CURRENT=0
    FREQUENCY=1
    VOLTAGE=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcSurfaceSide():
    """"""
    POSITIVE=0
    NEGATIVE=1
    BOTH=2
 
class IfcSpaceHeaterTypeEnum():
    """"""
    SECTIONALRADIATOR=0
    PANELRADIATOR=1
    TUBULARRADIATOR=2
    CONVECTOR=3
    BASEBOARDHEATER=4
    FINNEDTUBEUNIT=5
    UNITHEATER=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcTubeBundleTypeEnum():
    """"""
    FINNED=0
    USERDEFINED=1
    NOTDEFINED=2
 
class IfcLightFixtureTypeEnum():
    """"""
    POINTSOURCE=0
    DIRECTIONSOURCE=1
    USERDEFINED=2
    NOTDEFINED=3
 
class IfcGlobalOrLocalEnum():
    """"""
    GLOBAL_COORDS=0
    LOCAL_COORDS=1
 
class IfcOutletTypeEnum():
    """"""
    AUDIOVISUALOUTLET=0
    COMMUNICATIONSOUTLET=1
    POWEROUTLET=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcWorkControlTypeEnum():
    """"""
    ACTUAL=0
    BASELINE=1
    PLANNED=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcEnergySequenceEnum():
    """"""
    PRIMARY=0
    SECONDARY=1
    TERTIARY=2
    AUXILIARY=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcVibrationIsolatorTypeEnum():
    """"""
    COMPRESSION=0
    SPRING=1
    USERDEFINED=2
    NOTDEFINED=3
 
class IfcTankTypeEnum():
    """"""
    PREFORMED=0
    SECTIONAL=1
    EXPANSION=2
    PRESSUREVESSEL=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcTimeSeriesDataTypeEnum():
    """"""
    CONTINUOUS=0
    DISCRETE=1
    DISCRETEBINARY=2
    PIECEWISEBINARY=3
    PIECEWISECONSTANT=4
    PIECEWISECONTINUOUS=5
    NOTDEFINED=6
 
class IfcSurfaceTextureEnum():
    """"""
    BUMP=0
    OPACITY=1
    REFLECTION=2
    SELFILLUMINATION=3
    SHININESS=4
    SPECULAR=5
    TEXTURE=6
    TRANSPARENCYMAP=7
    NOTDEFINED=8
 
class IfcAddressTypeEnum():
    """"""
    OFFICE=0
    SITE=1
    HOME=2
    DISTRIBUTIONPOINT=3
    USERDEFINED=4
 
class IfcChillerTypeEnum():
    """"""
    AIRCOOLED=0
    WATERCOOLED=1
    HEATRECOVERY=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcLightDistributionCurveEnum():
    """"""
    TYPE_A=0
    TYPE_B=1
    TYPE_C=2
    NOTDEFINED=3
 
class IfcReinforcingBarRoleEnum():
    """"""
    MAIN=0
    SHEAR=1
    LIGATURE=2
    STUD=3
    PUNCHING=4
    EDGE=5
    RING=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcResourceConsumptionEnum():
    """"""
    CONSUMED=0
    PARTIALLYCONSUMED=1
    NOTCONSUMED=2
    OCCUPIED=3
    PARTIALLYOCCUPIED=4
    NOTOCCUPIED=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcEvaporatorTypeEnum():
    """"""
    DIRECTEXPANSIONSHELLANDTUBE=0
    DIRECTEXPANSIONTUBEINTUBE=1
    DIRECTEXPANSIONBRAZEDPLATE=2
    FLOODEDSHELLANDTUBE=3
    SHELLANDCOIL=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcTimeSeriesScheduleTypeEnum():
    """"""
    ANNUAL=0
    MONTHLY=1
    WEEKLY=2
    DAILY=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcElectricMotorTypeEnum():
    """"""
    DC=0
    INDUCTION=1
    POLYPHASE=2
    RELUCTANCESYNCHRONOUS=3
    SYNCHRONOUS=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcDoorPanelOperationEnum():
    """"""
    SWINGING=0
    DOUBLE_ACTING=1
    SLIDING=2
    FOLDING=3
    REVOLVING=4
    ROLLINGUP=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcWindowPanelOperationEnum():
    """"""
    SIDEHUNGRIGHTHAND=0
    SIDEHUNGLEFTHAND=1
    TILTANDTURNRIGHTHAND=2
    TILTANDTURNLEFTHAND=3
    TOPHUNG=4
    BOTTOMHUNG=5
    PIVOTHORIZONTAL=6
    PIVOTVERTICAL=7
    SLIDINGHORIZONTAL=8
    SLIDINGVERTICAL=9
    REMOVABLECASEMENT=10
    FIXEDCASEMENT=11
    OTHEROPERATION=12
    NOTDEFINED=13
 
class IfcDataOriginEnum():
    """"""
    MEASURED=0
    PREDICTED=1
    SIMULATED=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcStairTypeEnum():
    """"""
    STRAIGHT_RUN_STAIR=0
    TWO_STRAIGHT_RUN_STAIR=1
    QUARTER_WINDING_STAIR=2
    QUARTER_TURN_STAIR=3
    HALF_WINDING_STAIR=4
    HALF_TURN_STAIR=5
    TWO_QUARTER_WINDING_STAIR=6
    TWO_QUARTER_TURN_STAIR=7
    THREE_QUARTER_WINDING_STAIR=8
    THREE_QUARTER_TURN_STAIR=9
    SPIRAL_STAIR=10
    DOUBLE_RETURN_STAIR=11
    CURVED_RUN_STAIR=12
    TWO_CURVED_RUN_STAIR=13
    USERDEFINED=14
    NOTDEFINED=15
 
class IfcRailingTypeEnum():
    """"""
    HANDRAIL=0
    GUARDRAIL=1
    BALUSTRADE=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcStackTerminalTypeEnum():
    """"""
    BIRDCAGE=0
    COWL=1
    RAINWATERHOPPER=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcValveTypeEnum():
    """"""
    AIRRELEASE=0
    ANTIVACUUM=1
    CHANGEOVER=2
    CHECK=3
    COMMISSIONING=4
    DIVERTING=5
    DRAWOFFCOCK=6
    DOUBLECHECK=7
    DOUBLEREGULATING=8
    FAUCET=9
    FLUSHING=10
    GASCOCK=11
    GASTAP=12
    ISOLATING=13
    MIXING=14
    PRESSUREREDUCING=15
    PRESSURERELIEF=16
    REGULATING=17
    SAFETYCUTOFF=18
    STEAMTRAP=19
    STOPCOCK=20
    USERDEFINED=21
    NOTDEFINED=22
 
class IfcWindowPanelPositionEnum():
    """"""
    LEFT=0
    MIDDLE=1
    RIGHT=2
    BOTTOM=3
    TOP=4
    NOTDEFINED=5
 
class IfcPropertySourceEnum():
    """"""
    DESIGN=0
    DESIGNMAXIMUM=1
    DESIGNMINIMUM=2
    SIMULATED=3
    ASBUILT=4
    COMMISSIONING=5
    MEASURED=6
    USERDEFINED=7
    NOTKNOWN=8
 
class IfcCableCarrierSegmentTypeEnum():
    """"""
    CABLELADDERSEGMENT=0
    CABLETRAYSEGMENT=1
    CABLETRUNKINGSEGMENT=2
    CONDUITSEGMENT=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcPhysicalOrVirtualEnum():
    """"""
    PHYSICAL=0
    VIRTUAL=1
    NOTDEFINED=2
 
class IfcSpaceTypeEnum():
    """"""
    USERDEFINED=0
    NOTDEFINED=1
 
class IfcEvaporativeCoolerTypeEnum():
    """"""
    DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER=0
    DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER=1
    DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER=2
    DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER=3
    DIRECTEVAPORATIVEAIRWASHER=4
    INDIRECTEVAPORATIVEPACKAGEAIRCOOLER=5
    INDIRECTEVAPORATIVEWETCOIL=6
    INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER=7
    INDIRECTDIRECTCOMBINATION=8
    USERDEFINED=9
    NOTDEFINED=10
 
class IfcHeatExchangerTypeEnum():
    """"""
    PLATE=0
    SHELLANDTUBE=1
    USERDEFINED=2
    NOTDEFINED=3
 
class IfcProtectiveDeviceTypeEnum():
    """"""
    FUSEDISCONNECTOR=0
    CIRCUITBREAKER=1
    EARTHFAILUREDEVICE=2
    RESIDUALCURRENTCIRCUITBREAKER=3
    RESIDUALCURRENTSWITCH=4
    VARISTOR=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcDamperTypeEnum():
    """"""
    CONTROLDAMPER=0
    FIREDAMPER=1
    SMOKEDAMPER=2
    FIRESMOKEDAMPER=3
    BACKDRAFTDAMPER=4
    RELIEFDAMPER=5
    BLASTDAMPER=6
    GRAVITYDAMPER=7
    GRAVITYRELIEFDAMPER=8
    BALANCINGDAMPER=9
    FUMEHOODEXHAUST=10
    USERDEFINED=11
    NOTDEFINED=12
 
class IfcControllerTypeEnum():
    """"""
    FLOATING=0
    PROPORTIONAL=1
    PROPORTIONALINTEGRAL=2
    PROPORTIONALINTEGRALDERIVATIVE=3
    TIMEDTWOPOSITION=4
    TWOPOSITION=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcAssemblyPlaceEnum():
    """"""
    SITE=0
    FACTORY=1
    NOTDEFINED=2
 
class IfcServiceLifeFactorTypeEnum():
    """"""
    A_QUALITYOFCOMPONENTS=0
    B_DESIGNLEVEL=1
    C_WORKEXECUTIONLEVEL=2
    D_INDOORENVIRONMENT=3
    E_OUTDOORENVIRONMENT=4
    F_INUSECONDITIONS=5
    G_MAINTENANCELEVEL=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcBeamTypeEnum():
    """"""
    BEAM=0
    JOIST=1
    LINTEL=2
    T_BEAM=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcStateEnum():
    """"""
    READWRITE=0
    READONLY=1
    LOCKED=2
    READWRITELOCKED=3
    READONLYLOCKED=4
 
class IfcSectionTypeEnum():
    """"""
    UNIFORM=0
    TAPERED=1
 
class IfcFootingTypeEnum():
    """"""
    FOOTING_BEAM=0
    PAD_FOOTING=1
    PILE_CAP=2
    STRIP_FOOTING=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcLoadGroupTypeEnum():
    """"""
    LOAD_GROUP=0
    LOAD_CASE=1
    LOAD_COMBINATION_GROUP=2
    LOAD_COMBINATION=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcElectricGeneratorTypeEnum():
    """"""
    USERDEFINED=0
    NOTDEFINED=1
 
class IfcFlowMeterTypeEnum():
    """"""
    ELECTRICMETER=0
    ENERGYMETER=1
    FLOWMETER=2
    GASMETER=3
    OILMETER=4
    WATERMETER=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcAnalysisModelTypeEnum():
    """"""
    IN_PLANE_LOADING_2D=0
    OUT_PLANE_LOADING_2D=1
    LOADING_3D=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcCurtainWallTypeEnum():
    """"""
    USERDEFINED=0
    NOTDEFINED=1
 
class IfcDoorPanelPositionEnum():
    """"""
    LEFT=0
    MIDDLE=1
    RIGHT=2
    NOTDEFINED=3
 
class IfcPlateTypeEnum():
    """"""
    CURTAIN_PANEL=0
    SHEET=1
    USERDEFINED=2
    NOTDEFINED=3
 
class IfcStructuralSurfaceTypeEnum():
    """"""
    BENDING_ELEMENT=0
    MEMBRANE_ELEMENT=1
    SHELL=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcAirToAirHeatRecoveryTypeEnum():
    """"""
    FIXEDPLATECOUNTERFLOWEXCHANGER=0
    FIXEDPLATECROSSFLOWEXCHANGER=1
    FIXEDPLATEPARALLELFLOWEXCHANGER=2
    ROTARYWHEEL=3
    RUNAROUNDCOILLOOP=4
    HEATPIPE=5
    TWINTOWERENTHALPYRECOVERYLOOPS=6
    THERMOSIPHONSEALEDTUBEHEATEXCHANGERS=7
    THERMOSIPHONCOILTYPEHEATEXCHANGERS=8
    USERDEFINED=9
    NOTDEFINED=10
 
class IfcDocumentStatusEnum():
    """"""
    DRAFT=0
    FINALDRAFT=1
    FINAL=2
    REVISION=3
    NOTDEFINED=4
 
class IfcRampTypeEnum():
    """"""
    STRAIGHT_RUN_RAMP=0
    TWO_STRAIGHT_RUN_RAMP=1
    QUARTER_TURN_RAMP=2
    TWO_QUARTER_TURN_RAMP=3
    HALF_TURN_RAMP=4
    SPIRAL_RAMP=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcConnectionTypeEnum():
    """"""
    ATPATH=0
    ATSTART=1
    ATEND=2
    NOTDEFINED=3
 
class IfcCoolingTowerTypeEnum():
    """"""
    NATURALDRAFT=0
    MECHANICALINDUCEDDRAFT=1
    MECHANICALFORCEDDRAFT=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcSwitchingDeviceTypeEnum():
    """"""
    CONTACTOR=0
    EMERGENCYSTOP=1
    STARTER=2
    SWITCHDISCONNECTOR=3
    TOGGLESWITCH=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcFlowDirectionEnum():
    """"""
    SOURCE=0
    SINK=1
    SOURCEANDSINK=2
    NOTDEFINED=3
 
class IfcThermalLoadSourceEnum():
    """"""
    PEOPLE=0
    LIGHTING=1
    EQUIPMENT=2
    VENTILATIONINDOORAIR=3
    VENTILATIONOUTSIDEAIR=4
    RECIRCULATEDAIR=5
    EXHAUSTAIR=6
    AIREXCHANGERATE=7
    DRYBULBTEMPERATURE=8
    RELATIVEHUMIDITY=9
    INFILTRATION=10
    USERDEFINED=11
    NOTDEFINED=12
 
class IfcAnalysisTheoryTypeEnum():
    """"""
    FIRST_ORDER_THEORY=0
    SECOND_ORDER_THEORY=1
    THIRD_ORDER_THEORY=2
    FULL_NONLINEAR_THEORY=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcTendonTypeEnum():
    """"""
    STRAND=0
    WIRE=1
    BAR=2
    COATED=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcElectricDistributionPointFunctionEnum():
    """"""
    ALARMPANEL=0
    CONSUMERUNIT=1
    CONTROLPANEL=2
    DISTRIBUTIONBOARD=3
    GASDETECTORPANEL=4
    INDICATORPANEL=5
    MIMICPANEL=6
    MOTORCONTROLCENTRE=7
    SWITCHBOARD=8
    USERDEFINED=9
    NOTDEFINED=10
 
class IfcActionTypeEnum():
    """"""
    PERMANENT_G=0
    VARIABLE_Q=1
    EXTRAORDINARY_A=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcReinforcingBarSurfaceEnum():
    """"""
    PLAIN=0
    TEXTURED=1
 
class IfcHumidifierTypeEnum():
    """"""
    STEAMINJECTION=0
    ADIABATICAIRWASHER=1
    ADIABATICPAN=2
    ADIABATICWETTEDELEMENT=3
    ADIABATICATOMIZING=4
    ADIABATICULTRASONIC=5
    ADIABATICRIGIDMEDIA=6
    ADIABATICCOMPRESSEDAIRNOZZLE=7
    ASSISTEDELECTRIC=8
    ASSISTEDNATURALGAS=9
    ASSISTEDPROPANE=10
    ASSISTEDBUTANE=11
    ASSISTEDSTEAM=12
    USERDEFINED=13
    NOTDEFINED=14
 
class IfcLayerSetDirectionEnum():
    """"""
    AXIS1=0
    AXIS2=1
    AXIS3=2
 
class IfcBoilerTypeEnum():
    """"""
    WATER=0
    STEAM=1
    USERDEFINED=2
    NOTDEFINED=3
 
class IfcElectricFlowStorageDeviceTypeEnum():
    """"""
    BATTERY=0
    CAPACITORBANK=1
    HARMONICFILTER=2
    INDUCTORBANK=3
    UPS=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcUnitEnum():
    """"""
    ABSORBEDDOSEUNIT=0
    AMOUNTOFSUBSTANCEUNIT=1
    AREAUNIT=2
    DOSEEQUIVALENTUNIT=3
    ELECTRICCAPACITANCEUNIT=4
    ELECTRICCHARGEUNIT=5
    ELECTRICCONDUCTANCEUNIT=6
    ELECTRICCURRENTUNIT=7
    ELECTRICRESISTANCEUNIT=8
    ELECTRICVOLTAGEUNIT=9
    ENERGYUNIT=10
    FORCEUNIT=11
    FREQUENCYUNIT=12
    ILLUMINANCEUNIT=13
    INDUCTANCEUNIT=14
    LENGTHUNIT=15
    LUMINOUSFLUXUNIT=16
    LUMINOUSINTENSITYUNIT=17
    MAGNETICFLUXDENSITYUNIT=18
    MAGNETICFLUXUNIT=19
    MASSUNIT=20
    PLANEANGLEUNIT=21
    POWERUNIT=22
    PRESSUREUNIT=23
    RADIOACTIVITYUNIT=24
    SOLIDANGLEUNIT=25
    THERMODYNAMICTEMPERATUREUNIT=26
    TIMEUNIT=27
    VOLUMEUNIT=28
    USERDEFINED=29
 
class IfcInventoryTypeEnum():
    """"""
    ASSETINVENTORY=0
    SPACEINVENTORY=1
    FURNITUREINVENTORY=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcElementAssemblyTypeEnum():
    """"""
    ACCESSORY_ASSEMBLY=0
    ARCH=1
    BEAM_GRID=2
    BRACED_FRAME=3
    GIRDER=4
    REINFORCEMENT_UNIT=5
    RIGID_FRAME=6
    SLAB_FIELD=7
    TRUSS=8
    USERDEFINED=9
    NOTDEFINED=10
 
class IfcServiceLifeTypeEnum():
    """"""
    ACTUALSERVICELIFE=0
    EXPECTEDSERVICELIFE=1
    OPTIMISTICREFERENCESERVICELIFE=2
    PESSIMISTICREFERENCESERVICELIFE=3
    REFERENCESERVICELIFE=4
 
class IfcCoveringTypeEnum():
    """"""
    CEILING=0
    FLOORING=1
    CLADDING=2
    ROOFING=3
    INSULATION=4
    MEMBRANE=5
    SLEEVING=6
    WRAPPING=7
    USERDEFINED=8
    NOTDEFINED=9
 
class IfcStairFlightTypeEnum():
    """"""
    STRAIGHT=0
    WINDER=1
    SPIRAL=2
    CURVED=3
    FREEFORM=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcSIPrefix():
    """"""
    EXA=0
    PETA=1
    TERA=2
    GIGA=3
    MEGA=4
    KILO=5
    HECTO=6
    DECA=7
    DECI=8
    CENTI=9
    MILLI=10
    MICRO=11
    NANO=12
    PICO=13
    FEMTO=14
    ATTO=15
 
class IfcFlowInstrumentTypeEnum():
    """"""
    PRESSUREGAUGE=0
    THERMOMETER=1
    AMMETER=2
    FREQUENCYMETER=3
    POWERFACTORMETER=4
    PHASEANGLEMETER=5
    VOLTMETER_PEAK=6
    VOLTMETER_RMS=7
    USERDEFINED=8
    NOTDEFINED=9
 
class IfcLampTypeEnum():
    """"""
    COMPACTFLUORESCENT=0
    FLUORESCENT=1
    HIGHPRESSUREMERCURY=2
    HIGHPRESSURESODIUM=3
    METALHALIDE=4
    TUNGSTENFILAMENT=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcTransportElementTypeEnum():
    """"""
    ELEVATOR=0
    ESCALATOR=1
    MOVINGWALKWAY=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcSoundScaleEnum():
    """"""
    DBA=0
    DBB=1
    DBC=2
    NC=3
    NR=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcActuatorTypeEnum():
    """"""
    ELECTRICACTUATOR=0
    HANDOPERATEDACTUATOR=1
    HYDRAULICACTUATOR=2
    PNEUMATICACTUATOR=3
    THERMOSTATICACTUATOR=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcDuctSegmentTypeEnum():
    """"""
    RIGIDSEGMENT=0
    FLEXIBLESEGMENT=1
    USERDEFINED=2
    NOTDEFINED=3
 
class IfcTransitionCode():
    """"""
    DISCONTINUOUS=0
    CONTINUOUS=1
    CONTSAMEGRADIENT=2
    CONTSAMEGRADIENTSAMECURVATURE=3
 
class IfcElectricApplianceTypeEnum():
    """"""
    COMPUTER=0
    DIRECTWATERHEATER=1
    DISHWASHER=2
    ELECTRICCOOKER=3
    ELECTRICHEATER=4
    FACSIMILE=5
    FREESTANDINGFAN=6
    FREEZER=7
    FRIDGE_FREEZER=8
    HANDDRYER=9
    INDIRECTWATERHEATER=10
    MICROWAVE=11
    PHOTOCOPIER=12
    PRINTER=13
    REFRIGERATOR=14
    RADIANTHEATER=15
    SCANNER=16
    TELEPHONE=17
    TUMBLEDRYER=18
    TV=19
    VENDINGMACHINE=20
    WASHINGMACHINE=21
    WATERHEATER=22
    WATERCOOLER=23
    USERDEFINED=24
    NOTDEFINED=25
 
class IfcProfileTypeEnum():
    """"""
    CURVE=0
    AREA=1
 
class IfcProjectedOrTrueLengthEnum():
    """"""
    PROJECTED_LENGTH=0
    TRUE_LENGTH=1
 
class IfcPileConstructionEnum():
    """"""
    CAST_IN_PLACE=0
    COMPOSITE=1
    PRECAST_CONCRETE=2
    PREFAB_STEEL=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcMotorConnectionTypeEnum():
    """"""
    BELTDRIVE=0
    COUPLING=1
    DIRECTDRIVE=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcOccupantTypeEnum():
    """"""
    ASSIGNEE=0
    ASSIGNOR=1
    LESSEE=2
    LESSOR=3
    LETTINGAGENT=4
    OWNER=5
    TENANT=6
    USERDEFINED=7
    NOTDEFINED=8
 
class IfcCondenserTypeEnum():
    """"""
    WATERCOOLEDSHELLTUBE=0
    WATERCOOLEDSHELLCOIL=1
    WATERCOOLEDTUBEINTUBE=2
    WATERCOOLEDBRAZEDPLATE=3
    AIRCOOLED=4
    EVAPORATIVECOOLED=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcEnvironmentalImpactCategoryEnum():
    """"""
    COMBINEDVALUE=0
    DISPOSAL=1
    EXTRACTION=2
    INSTALLATION=3
    MANUFACTURE=4
    TRANSPORTATION=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcLogicalOperatorEnum():
    """"""
    LOGICALAND=0
    LOGICALOR=1
 
class IfcCompressorTypeEnum():
    """"""
    DYNAMIC=0
    RECIPROCATING=1
    ROTARY=2
    SCROLL=3
    TROCHOIDAL=4
    SINGLESTAGE=5
    BOOSTER=6
    OPENTYPE=7
    HERMETIC=8
    SEMIHERMETIC=9
    WELDEDSHELLHERMETIC=10
    ROLLINGPISTON=11
    ROTARYVANE=12
    SINGLESCREW=13
    TWINSCREW=14
    USERDEFINED=15
    NOTDEFINED=16
 
class IfcBenchmarkEnum():
    """"""
    GREATERTHAN=0
    GREATERTHANOREQUALTO=1
    LESSTHAN=2
    LESSTHANOREQUALTO=3
    EQUALTO=4
    NOTEQUALTO=5
 
class IfcConstraintEnum():
    """"""
    HARD=0
    SOFT=1
    ADVISORY=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcAlarmTypeEnum():
    """"""
    BELL=0
    BREAKGLASSBUTTON=1
    LIGHT=2
    MANUALPULLBOX=3
    SIREN=4
    WHISTLE=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcArithmeticOperatorEnum():
    """"""
    ADD=0
    DIVIDE=1
    MULTIPLY=2
    SUBTRACT=3
 
class IfcTrimmingPreference():
    """"""
    CARTESIAN=0
    PARAMETER=1
    UNSPECIFIED=2
 
class IfcPipeSegmentTypeEnum():
    """"""
    FLEXIBLESEGMENT=0
    RIGIDSEGMENT=1
    GUTTER=2
    SPOOL=3
    USERDEFINED=4
    NOTDEFINED=5
 
class IfcDuctSilencerTypeEnum():
    """"""
    FLATOVAL=0
    RECTANGULAR=1
    ROUND=2
    USERDEFINED=3
    NOTDEFINED=4
 
class IfcChangeActionEnum():
    """"""
    NOCHANGE=0
    MODIFIED=1
    ADDED=2
    DELETED=3
    MODIFIEDADDED=4
    MODIFIEDDELETED=5
 
class IfcCoilTypeEnum():
    """"""
    DXCOOLINGCOIL=0
    WATERCOOLINGCOIL=1
    STEAMHEATINGCOIL=2
    WATERHEATINGCOIL=3
    ELECTRICHEATINGCOIL=4
    GASHEATINGCOIL=5
    USERDEFINED=6
    NOTDEFINED=7
 
class IfcStructuralCurveTypeEnum():
    """"""
    RIGID_JOINED_MEMBER=0
    PIN_JOINED_MEMBER=1
    CABLE=2
    TENSION_MEMBER=3
    COMPRESSION_MEMBER=4
    USERDEFINED=5
    NOTDEFINED=6
 
class IfcPermeableCoveringOperationEnum():
    """"""
    GRILL=0
    LOUVER=1
    SCREEN=2
    USERDEFINED=3
    NOTDEFINED=4
 
