#!/usr/bin/python
#coding=utf-8
#Filename:IfcDerivedMeasureValue.py

#TYPE IfcDerivedMeasureValue = SELECT
	#(IfcVolumetricFlowRateMeasure,IfcTimeStamp,IfcThermalTransmittanceMeasure,IfcThermalResistanceMeasure,IfcThermalAdmittanceMeasure,IfcPressureMeasure,IfcPowerMeasure,IfcMassFlowRateMeasure,IfcMassDensityMeasure,IfcLinearVelocityMeasure,IfcKinematicViscosityMeasure,IfcIntegerCountRateMeasure,IfcHeatFluxDensityMeasure,IfcFrequencyMeasure,IfcEnergyMeasure,IfcElectricVoltageMeasure,IfcDynamicViscosityMeasure,IfcCompoundPlaneAngleMeasure,IfcAngularVelocityMeasure,IfcThermalConductivityMeasure,IfcMolecularWeightMeasure,IfcVaporPermeabilityMeasure,IfcMoistureDiffusivityMeasure,IfcIsothermalMoistureCapacityMeasure,IfcSpecificHeatCapacityMeasure,IfcMonetaryMeasure,IfcMagneticFluxDensityMeasure,IfcMagneticFluxMeasure,IfcLuminousFluxMeasure,IfcForceMeasure,IfcInductanceMeasure,IfcIlluminanceMeasure,IfcElectricResistanceMeasure,IfcElectricConductanceMeasure,IfcElectricChargeMeasure,IfcDoseEquivalentMeasure,IfcElectricCapacitanceMeasure,IfcAbsorbedDoseMeasure,IfcRadioActivityMeasure,IfcRotationalFrequencyMeasure,IfcTorqueMeasure,IfcAccelerationMeasure,IfcLinearForceMeasure,IfcLinearStiffnessMeasure,IfcModulusOfSubgradeReactionMeasure,IfcModulusOfElasticityMeasure,IfcMomentOfInertiaMeasure,IfcPlanarForceMeasure,IfcRotationalStiffnessMeasure,IfcShearModulusMeasure,IfcLinearMomentMeasure,IfcLuminousIntensityDistributionMeasure,IfcCurvatureMeasure,IfcMassPerLengthMeasure,IfcModulusOfLinearSubgradeReactionMeasure,IfcModulusOfRotationalSubgradeReactionMeasure,IfcRotationalMassMeasure,IfcSectionalAreaIntegralMeasure,IfcSectionModulusMeasure,IfcTemperatureGradientMeasure,IfcThermalExpansionCoefficientMeasure,IfcWarpingConstantMeasure,IfcWarpingMomentMeasure,IfcSoundPowerMeasure,IfcSoundPressureMeasure,IfcHeatingValueMeasure,IfcPHMeasure,IfcIonConcentrationMeasure);
#END_TYPE;

class IfcDerivedMeasureValue(object):
    """"""
    def __init__(self,obj):
        super(IfcDerivedMeasureValue,self).__init__()
        self.lid=obj.lid
        self.m_type=obj.type
        
